# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

parameters:
  - name: Proyecto
	type: string
	displayName: 'Seleccione proyecto'
	values:
      - UserProfileService
  - name: Testing
	type: boolean
	displayName: 'Ejecutar tests'
	default: true

trigger: none

jobs:
  - job: build
    displayName: Build and Test
	pool:
	  name: Windows
	steps:
	- script: echo building $(Build.BuildNumber)
    - ${{ if eq(parameters.Testing, true) }}:
      - script: echo "Running all the tests"


