# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

parameters:
  - name: Proyecto
    type: string
    displayName: 'Seleccione proyecto'
    default: UserProfileService
    values:
    - UserProfileService
    - ContentManagementService
  - name: Testing
    type: boolean
    displayName: 'Ejecutar tests'
    default: true

trigger: none

jobs:
- job: build
  displayName: Build and Test
  pool:
    name: Windows
  steps:
  - task: MSBuild@1
    inputs:
      solution: './apps/${{ parameters.Proyecto }}/*.csproj'
      msbuildVersion: '17.0'
      msbuildArchitecture: 'x64'
      restoreNugetPackages: true