# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

parameters:
  - name: Proyecto
    type: string
    displayName: 'Seleccione proyecto'
    default: UserProfileService
    values:
    - UserProfileService
    - ContentManagementService
  - name: Testing
    type: boolean
    displayName: 'Ejecutar tests'
    default: true

trigger: none

jobs:
- job: build
  displayName: Build and Test
  pool:
    name: Windows
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    name: Build
    inputs:
      command: 'build'
      projects: 'apps/${{ parameters.Proyecto }}/${{ parameters.Proyecto }}.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Test project'
    condition: ${{ eq(parameters.Testing, true) }}
    name: Test
    inputs:
      command: 'test'
      projects: 'tests/${{ parameters.Proyecto }}.Tests/${{ parameters.Proyecto }}.csproj'